#!/usr/bin/env python3
"""
Dynamical validation of the ideal-gas PPPM-Lanczos finite-time FDT thermostat (screened pure-longitudinal Markovian
model), in the spirit of Figs. 1-3 of Wang et al., PRL 131, 177301 (2023):
    Fig. 1  velocity autocorrelation C_V(t)
    Fig. 2  distance-conditioned velocity cross-correlation C_vv(t; r0), plus its components along / across r_ij(0)
    Fig. 3  longitudinal and transverse hydrodynamic-mode correlations C_L(k, t), C_T(k, t)

The simulator is NOT modified: trajectories are generated by calling test_true_dynamics.step unchanged (methods
"dense", "lanczos_hi", "rank40"); the production damping rank 16 is selected through the module constant RD.
The earlier dynamics runs saved only observables (no q_i(t), p_i(t)), so this script records them.

Equilibrium start: for U = 0 the stationary law is q uniform, p ~ N(0, beta^{-1} m Pi) (total momentum 0), and
A(dt/2) O(dt) A(dt/2) preserves it exactly, so every time origin is an equilibrium origin.

Stages:
    --stage generate --method M --seed S      one trajectory -> dynamics_results/correlations_raw/ (not committed)
    --stage analyze                           correlations, frozen-Gamma predictions, figures, JSON, report
"""
import argparse
import json
import sys
import time
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import test_true_dynamics as TD  # noqa: E402
from test_lanczos_fdt import DenseRef  # noqa: E402

OUT = TD.OUT / "correlations"
RAW = TD.OUT / "correlations_raw"
N_DEF, NSTEPS_DEF = 512, 600
KAPPA = 1.0                                     # screening length 1/kappa = 1
R0 = np.array([0.5, 1.0, 2.0, 3.0, 4.0]) / KAPPA
DR = 0.5 / KAPPA
ORIGIN_STRIDE = 5
T_LAG_VACF, T_LAG_VCCF, T_LAG_MODE = 6.0, 6.0, 14.0
NVEC = [(1, 0, 0), (0, 1, 0), (0, 0, 1),
        (1, 1, 0), (1, -1, 0), (1, 0, 1), (1, 0, -1), (0, 1, 1), (0, 1, -1),
        (2, 0, 0), (0, 2, 0), (0, 0, 2)]
METHODS = ["dense", "lanczos_hi", "rank40"]
LABEL = {"dense": "dense reference", "lanczos_hi": "PPPM + high-rank Lanczos (90/24)",
         "rank40": "PPPM + production Lanczos (40/16)"}
PAL = {"dense": "#222222", "lanczos_hi": "#2a78d6", "rank40": "#eb6834"}
COUPLED_SEEDS = (0, 1)


def raw_path(method, seed, N):
    return RAW / f"traj_N{N}_{method}_seed{seed}.npz"


# ----------------------------------------------------------------------------
# Trajectory generation (unchanged simulator)
# ----------------------------------------------------------------------------
def equilibrium_state(N, L, seed):
    rng = np.random.default_rng([20261006, seed, 0])
    q = rng.uniform(0, L, size=(N, 3))
    p = rng.normal(size=(N, 3)) * np.sqrt(TD.MASS / TD.BETA)
    return q, p - p.mean(axis=0)


def generate(method, seed, N, nsteps, say):
    TD.RD = 16                                                  # production damping rank
    dt = json.loads((TD.OUT / "params_small.json").read_text())["dt"]
    box = TD.Box(N)
    q, p = equilibrium_state(N, box.L, seed)
    xis = np.random.default_rng([20261006, seed, 1]).normal(size=(nsteps, N, 3))   # common stream for all methods
    Q = np.empty((nsteps + 1, N, 3))
    P = np.empty((nsteps + 1, N, 3))
    Q[0], P[0] = q, p
    lam = np.empty((nsteps, 2))
    t0 = time.perf_counter()
    for n in range(nsteps):
        q, p, info = TD.step(box, q, p, xis[n], dt, method)
        Q[n + 1], P[n + 1] = q, p
        lam[n] = info["lam_min"], info["lam_max"]
    RAW.mkdir(parents=True, exist_ok=True)
    np.savez(raw_path(method, seed, N), q=Q, p=P, dt=dt, L=box.L, lam=lam, damping_rank=TD.RD,
             wall=time.perf_counter() - t0)
    say(f"{method} seed {seed}: {nsteps} steps in {time.perf_counter() - t0:.0f} s; "
        f"max |P| {np.abs(P.sum(axis=1)).max():.1e}; dt*lam_max <= {dt * lam[:, 1].max():.2f}")


# ----------------------------------------------------------------------------
# Correlation estimators (all time origins / strided origins, vectorised)
# ----------------------------------------------------------------------------
def fft_xcorr(a, nlag):
    """sum over trailing axes and over all origins of a(t0+l) conj(a(t0)) / (number of origins), l < nlag."""
    T = a.shape[0]
    n = 1 << int(np.ceil(np.log2(2 * T)))
    F = np.fft.fft(a.reshape(T, -1), n=n, axis=0)
    c = np.fft.ifft((F * F.conj()).sum(axis=1))[:nlag]
    return c / (T - np.arange(nlag))


def vacf_sums(V, nlag):
    """<sum_i v_i(t) . v_i(0)> over all origins."""
    return fft_xcorr(V, nlag).real


def pairs_at(q, L, rmax):
    """Ordered pairs (i != j) with minimum-image |r_ij| < rmax; returns i, j, r_ij vectors."""
    d = q[None, :, :] - q[:, None, :]
    d -= L * np.round(d / L)
    r = np.linalg.norm(d, axis=-1)
    i, j = np.nonzero((r < rmax) & (r > 0))
    return i, j, d[i, j]


def vccf_sums(Q, V, L, nlag, stride):
    """Bin-summed v_i(0).v_j(t), (v_i(0).e)(v_j(t).e) with e = r_ij(0)/|r_ij(0)|, and pair counts."""
    edges_lo, edges_hi = R0 - DR / 2, R0 + DR / 2
    origins = np.arange(0, V.shape[0] - nlag + 1, stride)
    S = np.zeros((nlag, len(R0)))
    Spar = np.zeros((nlag, len(R0)))
    cnt = np.zeros(len(R0))
    for o in origins:
        i, j, d = pairs_at(Q[o], L, edges_hi[-1])
        r = np.linalg.norm(d, axis=1)
        b = np.searchsorted(edges_hi, r)
        keep = (b < len(R0)) & (r >= edges_lo[np.minimum(b, len(R0) - 1)])
        i, j, d, r, b = i[keep], j[keep], d[keep], r[keep], b[keep]
        e = d / r[:, None]
        B = np.zeros((len(b), len(R0)))
        B[np.arange(len(b)), b] = 1.0
        Vi = V[o, i]
        Vj = V[o:o + nlag, j]
        S += np.einsum("pa,lpa->lp", Vi, Vj) @ B
        Spar += (np.einsum("pa,pa->p", Vi, e)[None, :] * np.einsum("lpa,pa->lp", Vj, e)) @ B
        cnt += B.sum(axis=0)
    return S, Spar, cnt, len(origins)


def mode_basis(L):
    n = np.array(NVEC, float)
    k = 2 * np.pi / L * n
    kh = k / np.linalg.norm(k, axis=1, keepdims=True)
    a = np.where(np.abs(kh[:, [0]]) < 0.9, np.array([[1.0, 0, 0]]), np.array([[0, 1.0, 0]]))
    e1 = np.cross(kh, a)
    e1 /= np.linalg.norm(e1, axis=1, keepdims=True)
    e2 = np.cross(kh, e1)
    return k, kh, e1, e2, np.linalg.norm(n, axis=1)


def mode_sums(Q, V, L, nlag):
    """Per-|n| shell: <u_L(t) u_L(0)*>, <u_T(t) u_T(0)*> (averaged over directions and the two transverse axes)."""
    k, kh, e1, e2, nn = mode_basis(L)
    N = V.shape[1]
    ph = np.exp(1j * np.einsum("tja,ka->tkj", Q, k))                   # (T, K, N)
    u = np.einsum("tkj,tja->tka", ph, V) / N                           # (T, K, 3)
    uL = np.einsum("tka,ka->tk", u, kh)
    uT = np.stack([np.einsum("tka,ka->tk", u, e1), np.einsum("tka,ka->tk", u, e2)], axis=-1)
    shells = np.unique(nn)
    CL = np.stack([fft_xcorr(uL[:, nn == s], nlag).real / (nn == s).sum() for s in shells], axis=1)
    CT = np.stack([fft_xcorr(uT[:, nn == s], nlag).real / (2 * (nn == s).sum()) for s in shells], axis=1)
    return CL, CT, shells, 2 * np.pi / L * shells


def analyze_traj(path):
    d = np.load(path)
    Q, V, L, dt = d["q"], d["p"] / TD.MASS, float(d["L"]), float(d["dt"])
    nl_v, nl_c, nl_m = (int(round(T / dt)) + 1 for T in (T_LAG_VACF, T_LAG_VCCF, T_LAG_MODE))
    v2 = float((V ** 2).sum(axis=(1, 2)).mean())                       # <sum_i |v_i|^2>
    cv = vacf_sums(V, nl_v)
    S, Spar, cnt, n_or = vccf_sums(Q, V, L, nl_c, ORIGIN_STRIDE)
    CL, CT, shells, kmag = mode_sums(Q, V, L, nl_m)
    return dict(dt=dt, L=L, N=V.shape[1], v2=v2, cv=cv, S=S, Spar=Spar, cnt=cnt, n_origins=n_or,
                CL=CL, CT=CT, shells=shells, kmag=kmag, mom=float(np.abs(V.sum(axis=1)).max()),
                lam=d["lam"], wall=float(d["wall"]))


def normalise(a):
    """Normalised correlations for one trajectory."""
    v1 = a["v2"] / a["N"]                                              # <|v_i|^2>
    return dict(CV=a["cv"] / a["v2"],
                Cvv=a["S"] / a["cnt"] / v1, Cpar=a["Spar"] / a["cnt"] / (v1 / 3),
                Cperp=(a["S"] - a["Spar"]) / a["cnt"] / (2 * v1 / 3),
                CL=a["CL"] / a["CL"][0], CT=a["CT"] / a["CT"][0])


# ----------------------------------------------------------------------------
# Frozen-configuration predictions: exp(-t Gamma_h(q0)/m) with Gamma_h fixed (no advection, no re-sampling)
# ----------------------------------------------------------------------------
def frozen_prediction(Q0s, L, N, times):
    box = TD.Box(N)
    k, kh, e1, e2, nn = mode_basis(L)
    shells = np.unique(nn)
    res = dict(CV=[], Cvv=[], Cpar=[], Cperp=[], CL=[], CT=[])
    for q0 in Q0s:
        op = box.gamma(q0)
        ref = DenseRef(op.dense(), N)
        U, lam = ref.U, ref.lam                                         # eigenpairs on Range(Pi)
        i, j, d = pairs_at(q0, L, R0[-1] + DR / 2)
        r = np.linalg.norm(d, axis=1)
        b = np.searchsorted(R0 + DR / 2, r)
        keep = (b < len(R0)) & (r >= (R0 - DR / 2)[np.minimum(b, len(R0) - 1)])
        i, j, d, r, b = i[keep], j[keep], d[keep], r[keep], b[keep]
        e = d / r[:, None]
        B = np.zeros((len(b), len(R0)))
        B[np.arange(len(b)), b] = 1.0
        ph = np.exp(1j * q0 @ k.T)                                      # (N, K)
        wL = (ph[:, :, None] * kh[None]).reshape(N, -1, 3)              # weights for u_L (unnormalised)
        U3 = U.reshape(N, 3, -1)
        aL = np.einsum("jka,jam->km", wL, U3)                           # projections on eigenvectors
        aT1 = np.einsum("jk,ka,jam->km", ph, e1, U3)
        aT2 = np.einsum("jk,ka,jam->km", ph, e2, U3)
        cv, cvv, cpar, cl, ct = [], [], [], [], []
        for t in times:
            g = np.exp(-t * lam / TD.MASS)
            cv.append(g.sum() / (3 * (N - 1)))
            E = (U * g) @ U.T                                           # exp(-t Gamma/m) Pi
            E4 = E.reshape(N, 3, N, 3)
            blk = E4[j, :, i, :]                                        # <v_j(t) v_i(0)^T> m/kT
            tr = np.einsum("paa->p", blk)
            par = np.einsum("pa,pab,pb->p", e, blk, e)
            cvv.append((tr @ B) / B.sum(0) / 3)
            cpar.append((par @ B) / B.sum(0))
            cl.append(np.array([(np.abs(aL[nn == s]) ** 2 * g).sum() / (np.abs(aL[nn == s]) ** 2).sum()
                                for s in shells]))
            ct.append(np.array([((np.abs(aT1[nn == s]) ** 2 + np.abs(aT2[nn == s]) ** 2) * g).sum()
                                / ((np.abs(aT1[nn == s]) ** 2 + np.abs(aT2[nn == s]) ** 2).sum()) for s in shells]))
        res["CV"].append(cv)
        res["Cvv"].append(cvv)
        res["Cpar"].append(cpar)
        res["Cperp"].append((3 * np.array(cvv) - np.array(cpar)) / 2)
        res["CL"].append(cl)
        res["CT"].append(ct)
    return {kk: np.mean(np.array(v), axis=0) for kk, v in res.items()}


# ----------------------------------------------------------------------------
def analyze(args, say):
    OUT.mkdir(parents=True, exist_ok=True)
    N = args.N
    A = {}
    for f in sorted(RAW.glob(f"traj_N{N}_*_seed*.npz")):
        m, s = f.stem.split("_", 2)[2].rsplit("_seed", 1)
        A[(m, int(s))] = analyze_traj(f)
        say(f"analysed {m} seed {s}")
    methods = [m for m in METHODS if any(k[0] == m for k in A)]
    a0 = next(iter(A.values()))
    dt, L = a0["dt"], a0["L"]
    Nn = {k: normalise(v) for k, v in A.items()}
    seeds = {m: sorted(s for (mm, s) in A if mm == m) for m in methods}
    coupled = {m: [s for s in COUPLED_SEEDS if s in seeds[m]] for m in methods}

    def stat(m, key, ss):
        x = np.array([Nn[(m, s)][key] for s in ss])
        return x.mean(axis=0), (x.std(axis=0, ddof=1) / np.sqrt(len(ss)) if len(ss) > 1 else np.zeros_like(x[0]))

    # frozen-Gamma prediction on the t = 0 configurations of the coupled seeds (dense reference trajectories)
    tf = np.linspace(0, T_LAG_VACF, 31)
    tf_m = np.linspace(0, T_LAG_MODE, 36)
    Q0s = [np.load(raw_path(methods[0], s, N))["q"][0] for s in coupled[methods[0]]]
    fz = frozen_prediction(Q0s, L, N, tf)
    fzm = frozen_prediction(Q0s, L, N, tf_m)
    say("frozen-Gamma predictions done")

    summary = dict(N=N, L=L, dt=dt, kappa=KAPPA, r0=R0.tolist(), dr=DR, origin_stride_vccf=ORIGIN_STRIDE,
                   seeds=seeds, coupled_seeds=coupled, damping_rank_production=16, methods={})
    for m in methods:
        ent = {}
        for key in ("CV", "Cvv", "Cpar", "Cperp", "CL", "CT"):
            mu, se = stat(m, key, seeds[m])
            muc, _ = stat(m, key, coupled[m])
            ent[key] = dict(mean_all=mu.tolist(), se_all=se.tolist(), mean_coupled=muc.tolist())
        ent["max_momentum"] = max(A[(m, s)]["mom"] for s in seeds[m])
        ent["max_dt_lam_max"] = max(float(dt * A[(m, s)]["lam"][:, 1].max()) for s in seeds[m])
        ent["min_lam_min"] = min(float(A[(m, s)]["lam"][:, 0].min()) for s in seeds[m])
        ent["wall_per_step"] = float(np.mean([A[(m, s)]["wall"] / len(A[(m, s)]["lam"]) for s in seeds[m]]))
        summary["methods"][m] = ent
    # coupled differences against dense
    diffs = {}
    if "dense" in methods:
        for m in methods:
            if m == "dense":
                continue
            dd = {}
            for key in ("CV", "Cvv", "Cpar", "CL", "CT"):
                dd[key] = float(max(np.abs(Nn[(m, s)][key] - Nn[("dense", s)][key]).max() for s in coupled[m]))
            dd["traj_p"] = float(max(np.abs(np.load(raw_path(m, s, N))["p"] - np.load(raw_path("dense", s, N))["p"]).max()
                                     for s in coupled[m]))
            diffs[m] = dd
    summary["max_abs_diff_vs_dense_coupled"] = diffs
    # Pathwise divergence of coupled trajectories, and a statistical test against single-trajectory scatter:
    # sigma1 = std over production seeds of one trajectory's estimate; the 2-seed mean difference of two
    # independent estimates has std sigma1, so |Delta| <= 2 sigma1 is the agreement criterion once paths decorrelate.
    div, stat_test = {}, {}
    if "dense" in methods:
        for m in methods:
            if m == "dense":
                continue
            div[m] = {str(s): np.abs(np.load(raw_path(m, s, N))["p"] - np.load(raw_path("dense", s, N))["p"]).max(axis=(1, 2)).tolist()
                      for s in coupled[m]}
            st = {}
            for key in ("CV", "Cvv", "Cpar", "Cperp", "CL", "CT"):
                sig = np.array([Nn[("rank40", s)][key] for s in seeds["rank40"]]).std(axis=0, ddof=1)
                dlt = np.abs(np.array(summary["methods"][m][key]["mean_coupled"]) -
                             np.array(summary["methods"]["dense"][key]["mean_coupled"]))
                z = dlt[1:] / sig[1:]
                st[key] = dict(max_z=float(z.max()), median_z=float(np.median(z)), frac_within_2sigma=float(np.mean(z <= 2)))
            gr = {}
            for sd, dv in div[m].items():
                dv = np.array(dv)
                g = np.where((dv > 1e-10) & (dv < 1e-2))[0]
                gr[sd] = float(np.polyfit(g * dt, np.log(dv[g]), 1)[0]) if len(g) > 5 else None
            st["divergence_rate"] = gr
            st["divergence_initial"] = {sd: float(np.array(dv)[1]) for sd, dv in div[m].items()}
            st["t_div_1e-3"] = {sd: float(np.argmax(np.array(dv) > 1e-3) * dt) for sd, dv in div[m].items()}
            stat_test[m] = st
    summary["divergence"] = div
    summary["stat_test_vs_dense"] = stat_test
    summary["sigma1_CV"] = np.array([Nn[("rank40", s)]["CV"] for s in seeds["rank40"]]).std(axis=0, ddof=1).tolist()
    _, se_cv = stat("rank40", "CV", seeds["rank40"])
    _, se_cvv = stat("rank40", "Cvv", seeds["rank40"])
    _, se_cl = stat("rank40", "CL", seeds["rank40"])
    summary["rank40_typical_se"] = dict(CV=float(np.median(se_cv[1:])), Cvv=np.median(se_cvv[1:], axis=0).tolist(),
                                        CL=np.median(se_cl[1:], axis=0).tolist())
    summary["pair_counts_per_origin"] = (A[("rank40", seeds["rank40"][0])]["cnt"] /
                                         A[("rank40", seeds["rank40"][0])]["n_origins"]).tolist()
    summary["frozen"] = dict(t=tf.tolist(), CV=fz["CV"].tolist(), Cvv=fz["Cvv"].tolist(), Cpar=fz["Cpar"].tolist(),
                             Cperp=fz["Cperp"].tolist(), t_modes=tf_m.tolist(), CL=fzm["CL"].tolist(),
                             CT=fzm["CT"].tolist())
    summary["k_shells"] = dict(n=a0["shells"].tolist(), k=a0["kmag"].tolist())
    # simple descriptive numbers
    r = summary["methods"]["rank40"]
    tv = np.arange(len(r["CV"]["mean_all"])) * dt
    cvm = np.array(r["CV"]["mean_all"])
    summary["vacf_t_half"] = float(np.interp(0.5, cvm[::-1], tv[::-1]))
    summary["vacf_t_1e"] = float(np.interp(np.exp(-1), cvm[::-1], tv[::-1]))
    summary["vacf_integral_D"] = float(np.trapezoid(cvm, tv) * a0["v2"] / a0["N"] / 3)
    (OUT / "correlations.json").write_text(json.dumps(summary, indent=1) + "\n")
    figures(summary, say)


# ----------------------------------------------------------------------------
def figures(S, say):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    dt = S["dt"]
    M = S["methods"]
    methods = list(M)
    sty = {"dense": dict(lw=2.4, ls="-"), "lanczos_hi": dict(lw=1.6, ls="--"), "rank40": dict(lw=1.2, ls=":")}

    # ---- Fig 1: VACF
    fig, axs = plt.subplots(2, 2, figsize=(12, 8.4))
    ax = axs.ravel()
    for m in methods:
        c = np.array(M[m]["CV"]["mean_coupled"])
        t = np.arange(len(c)) * dt
        ax[0].plot(t, c, color=PAL[m], label=f"{LABEL[m]} (seeds {S['coupled_seeds'][m]})", **sty[m])
        ax[1].semilogy(t, np.abs(c), color=PAL[m], **sty[m])
    r = M["rank40"]["CV"]
    c, se = np.array(r["mean_all"]), np.array(r["se_all"])
    t = np.arange(len(c)) * dt
    ax[0].fill_between(t, c - 2 * se, c + 2 * se, color=PAL["rank40"], alpha=0.2,
                       label=f"production, {len(S['seeds']['rank40'])} seeds, ±2 SE")
    ax[0].plot(S["frozen"]["t"], S["frozen"]["CV"], "o", ms=3.5, mfc="none", color="#1baf7a",
               label="frozen-Γ_h prediction tr e^{-tΓ/m}Π / 3(N−1)")
    ax[1].semilogy(S["frozen"]["t"], S["frozen"]["CV"], "o", ms=3.5, mfc="none", color="#1baf7a")
    ax[0].axhline(0, color="0.7", lw=0.6)
    ax[0].set(xlabel="t", ylabel="C_V(t)", title="(a) normalised VACF")
    ax[1].set(xlabel="t", ylabel="|C_V(t)|", title="(b) semilog")
    ax[0].legend(fontsize=7)
    for m, dv in S["divergence"].items():
        for k_, (sd, d) in enumerate(dv.items()):
            d = np.array(d)
            ax[2].semilogy(np.arange(len(d)) * dt, np.maximum(d, 1e-17), color=PAL[m], ls=["-", "--"][k_ % 2],
                           label=f"{m} − dense, seed {sd}")
    tt = np.arange(len(d)) * dt
    ax[2].semilogy(tt, 1e-10 * np.exp(tt), color="0.5", lw=0.8, ls=":", label="∝ e^{t}")
    ax[2].set(xlabel="t", ylabel="max_i |p_i − p_i^dense|", title="(c) coupled-path divergence (same q0, p0, ξ)",
              ylim=(1e-12, 1e1))
    ax[2].legend(fontsize=7)
    sig = np.array(S["sigma1_CV"])
    for m in methods:
        if m == "dense":
            continue
        dmax = np.abs(np.array(M[m]["CV"]["mean_coupled"]) - np.array(M["dense"]["CV"]["mean_coupled"]))
        ax[3].semilogy(t[1:], np.maximum(dmax[1:], 1e-17), color=PAL[m], label=f"|{m} − dense| (2-seed means)")
    ax[3].semilogy(t[1:], 2 * sig[1:], color="0.4", ls="--", label="2σ₁ (single-trajectory scatter)")
    ax[3].set(xlabel="t", ylabel="|ΔC_V|", title="(d) VACF difference vs statistical scatter")
    ax[3].legend(fontsize=7)
    fig.suptitle(f"Fig. 1  VACF, ideal gas, N = {S['N']}, screened longitudinal Γ_h (1/κ = 1)", fontsize=10)
    fig.tight_layout()
    fig.savefig(OUT / "fig1_vacf.png", dpi=130)
    plt.close(fig)

    # ---- Fig 2: VCCF per distance bin, total and along / across r_ij(0)
    R0l = S["r0"]
    fig, ax = plt.subplots(3, len(R0l), figsize=(3.3 * len(R0l), 8.6), sharex=True)
    t = np.arange(len(M["rank40"]["Cvv"]["mean_all"])) * dt
    for col, r0 in enumerate(R0l):
        for row, key, name in ((0, "Cvv", "C_vv = <v_i(0)·v_j(t)> / <|v|²>"),
                               (1, "Cpar", "C_∥ (along r̂_ij(0))"), (2, "Cperp", "C_⊥ (across r̂_ij(0))")):
            a = ax[row, col]
            for m in methods:
                c = np.array(M[m][key]["mean_coupled"])[:, col]
                a.plot(t, c, color=PAL[m], **sty[m], label=LABEL[m] if (row == 0 and col == 0) else None)
            c, se = np.array(M["rank40"][key]["mean_all"])[:, col], np.array(M["rank40"][key]["se_all"])[:, col]
            a.fill_between(t, c - 2 * se, c + 2 * se, color=PAL["rank40"], alpha=0.2,
                           label="production, all seeds ±2 SE" if (row == 0 and col == 0) else None)
            fr = np.array(S["frozen"][key])[:, col]
            a.plot(S["frozen"]["t"], fr, "o", ms=3, mfc="none", color="#1baf7a",
                   label="frozen-Γ_h prediction" if (row == 0 and col == 0) else None)
            a.axhline(0, color="0.7", lw=0.6)
            a.axhline(-1 / (S["N"] - 1), color="0.7", lw=0.6, ls=":")
            if row == 0:
                a.set_title(f"r0 = {r0:g}/κ ± {S['dr'] / 2:g}", fontsize=9)
            if col == 0:
                a.set_ylabel(name, fontsize=8)
            if row == 2:
                a.set_xlabel("t")
    ax[0, 0].legend(fontsize=6)
    fig.suptitle("Fig. 2  distance-conditioned VCCF (dotted: momentum-constraint baseline −1/(N−1))", fontsize=10)
    fig.tight_layout()
    fig.savefig(OUT / "fig2_vccf.png", dpi=130)
    plt.close(fig)

    # ---- Fig 3: hydrodynamic modes
    ks = S["k_shells"]
    fig, ax = plt.subplots(2, len(ks["k"]), figsize=(4.4 * len(ks["k"]), 7.2), sharex=True)
    t = np.arange(len(M["rank40"]["CL"]["mean_all"])) * dt
    for col, (nn, k) in enumerate(zip(ks["n"], ks["k"])):
        for row, key, name in ((0, "CL", "C_L(k, t)"), (1, "CT", "C_T(k, t)")):
            a = ax[row, col]
            for m in methods:
                a.plot(t, np.array(M[m][key]["mean_coupled"])[:, col], color=PAL[m], **sty[m],
                       label=LABEL[m] if (row == 0 and col == 0) else None)
            c, se = np.array(M["rank40"][key]["mean_all"])[:, col], np.array(M["rank40"][key]["se_all"])[:, col]
            a.fill_between(t, c - 2 * se, c + 2 * se, color=PAL["rank40"], alpha=0.2,
                           label="production, all seeds ±2 SE" if (row == 0 and col == 0) else None)
            a.plot(S["frozen"]["t_modes"], np.array(S["frozen"][key])[:, col], "o", ms=3, mfc="none", color="#1baf7a",
                   label="frozen-Γ_h prediction" if (row == 0 and col == 0) else None)
            x2 = (k * t) ** 2 * TD.BETA ** -1 / TD.MASS
            a.plot(t, (1 - x2) * np.exp(-x2 / 2) if key == "CL" else np.exp(-x2 / 2), color="#8a8a8a", lw=1, ls="-.",
                   label="free streaming, no thermostat" if (row == 0 and col == 0) else None)
            a.axhline(0, color="0.7", lw=0.6)
            if row == 0:
                a.set_title(f"|n| = {nn:.3g}, k = {k:.3f}", fontsize=9)
            if col == 0:
                a.set_ylabel(name)
            if row == 1:
                a.set_xlabel("t")
    ax[0, 0].legend(fontsize=7)
    fig.suptitle("Fig. 3  longitudinal (top) and transverse (bottom) hydrodynamic-mode correlations, "
                 "ũ(k,t) = N⁻¹ Σ_j v_j e^{ik·q_j}", fontsize=10)
    fig.tight_layout()
    fig.savefig(OUT / "fig3_hydro_modes.png", dpi=130)
    plt.close(fig)
    say("figures written")


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--stage", choices=["generate", "analyze"], required=True)
    ap.add_argument("--method", choices=METHODS)
    ap.add_argument("--seed", type=int)
    ap.add_argument("--N", type=int, default=N_DEF)
    ap.add_argument("--nsteps", type=int, default=NSTEPS_DEF)
    args = ap.parse_args()
    say = lambda s: print(s, flush=True)       # noqa: E731
    if args.stage == "generate":
        generate(args.method, args.seed, args.N, args.nsteps, say)
    else:
        analyze(args, say)


if __name__ == "__main__":
    main()
